#!/usr/bin/env python
# -*- coding: utf-8 -*-

SPOT_RED = 0
SPOT_GREEN = 1
SPOT_BLUE = 0

SPOT_COLOUR = (SPOT_RED, SPOT_GREEN, SPOT_BLUE)

FISH_RED =  0.6
FISH_GREEN = 0.6
FISH_BLUE = 0.6

FISH_COLOUR = (FISH_RED, FISH_GREEN, FISH_BLUE)

WALL_RED =  1
WALL_GREEN = 0
WALL_BLUE = 0

WALL_COLOUR = (WALL_RED, WALL_GREEN, WALL_BLUE)
